name: Run tests

on:
  workflow_dispatch:

  pull_request:
    branches: ['dev', 'main']

env:
  node_version: 20

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node_version }}
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm test