name: Run tests

# Controls when the action will run.
on:
  workflow_dispatch:

  pull_request:
    branches: ['dev']

env:
  node_version: 20

jobs:
  tests:
    name: Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3
      with:
        version: latest

    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node_version }}
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm test